export const API_BASE_URL = '/api/v1'

export const ROUTES = {
  dashboard: '/',
  prompts: '/prompts',
  promptDetail: (id: string) => `/prompts/${id}`,
  promptPlayground: (id: string) => `/prompts/${id}/playground`,
  promptCompare: (id: string) => `/prompts/${id}/compare`,
  experiments: '/experiments',
  experimentNew: '/experiments/new',
  experimentDetail: (id: string) => `/experiments/${id}`,
  evaluations: '/evaluations',
  evalRunDetail: (id: string) => `/evaluations/runs/${id}`,
  evalDatasets: '/evaluations/datasets',
  humanEval: '/evaluations/human',
  humanEvalNew: '/evaluations/human/new',
  humanEvalDetail: (id: string) => `/evaluations/human/${id}`,
  humanEvalRate: (id: string) => `/evaluations/human/${id}/rate`,
  cost: '/cost',
  costAnalytics: '/cost/analytics',
  costRouting: '/cost/routing',
  costAlerts: '/cost/alerts',
  costForecast: '/cost/forecast',
  observability: '/observability',
  traces: '/observability/traces',
  traceDetail: (id: string) => `/observability/traces/${id}`,
  deployments: '/deployments',
  deploymentDetail: (id: string) => `/deployments/${id}`,
} as const
